name: tally_khata
description: ট্যালি খাতা - আয়-ব্যয় ট্র্যাকিং অ্যাপ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Share প্যাকেজ
  share_plus: ^10.1.4
  
  # Firebase প্যাকেজ
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  
  # অন্যান্য প্যাকেজ
  google_fonts: ^6.1.0
  intl: ^0.19.0
  fl_chart: ^0.69.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true