name: tally_khata
description: ট্যালি খাতা - আয়-ব্যয় ট্র্যাকিং অ্যাপ
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # প্যাকেজগুলোর ভার্সন Zapp-এর জন্য কমিয়ে দেওয়া হলো
  share_plus: ^7.0.0
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.6.0
  google_fonts: ^4.0.0
  intl: ^0.18.0
  fl_chart: ^0.60.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
